# Generated by Django 2.2 on 2019-04-10 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designTrip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designtrip',
            old_name='agent_byeby',
            new_name='agent_byebye',
        ),
    ]
