# Generated by Django 2.2 on 2019-04-10 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designTrip', '0002_auto_20190410_1647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DesignTrip',
        ),
    ]
