# Generated by Django 2.2 on 2019-04-10 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('designTrip', '0003_delete_designtrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_type', models.CharField(blank=True, max_length=50)),
                ('about_trip', models.CharField(blank=True, max_length=50)),
                ('budget', models.IntegerField(blank=True)),
                ('travel_with', models.CharField(blank=True, max_length=50)),
                ('couple_question', models.CharField(blank=True, max_length=50)),
                ('adult_number', models.IntegerField(blank=True)),
                ('chidren_number', models.IntegerField(blank=True)),
                ('exact_date', models.CharField(blank=True, max_length=50)),
                ('arrival_date', models.DateField(blank=True)),
                ('departure_date', models.DateField(blank=True)),
                ('month', models.CharField(blank=True, max_length=50)),
                ('period', models.CharField(blank=True, max_length=50)),
                ('begin_trip', models.CharField(blank=True, max_length=50)),
                ('agent_language', models.CharField(blank=True, max_length=50)),
                ('agent_time', models.CharField(blank=True, max_length=50)),
                ('agent_welcome', models.CharField(blank=True, max_length=50)),
                ('agent_byebye', models.CharField(blank=True, max_length=50)),
                ('agent_car', models.CharField(blank=True, max_length=50)),
                ('agent_camera', models.CharField(blank=True, max_length=50)),
                ('additional_info', models.TextField(blank=True, max_length=1000)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
