# Generated by Django 2.2 on 2019-04-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designTrip', '0004_designtrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designtrip',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designtrip',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
