# Generated by Django 2.2 on 2019-04-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designTrip', '0005_auto_20190410_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='designtrip',
            name='form_submitted_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
