# Generated by Django 2.2 on 2019-04-16 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designTrip', '0009_auto_20190416_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designtrip',
            name='program',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='designTrip.Program'),
        ),
    ]
