# Generated by Django 2.2 on 2019-04-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('historical', models.BooleanField(default=False)),
                ('local_culture', models.BooleanField(default=False)),
                ('local_cusine', models.BooleanField(default=False)),
                ('relaxation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribed_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
            ],
        ),
    ]
