# Generated by Django 2.2 on 2019-04-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripPackages', '0002_auto_20190416_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='year_in_school',
            field=models.CharField(choices=[('historical', 'historical'), ('local_culture', 'local_culture'), ('local_cusine', 'local_cusine'), ('relaxation', 'Senrelaxationior')], default='historical', max_length=2),
        ),
    ]
