# Generated by Django 2.2 on 2019-04-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripPackages', '0003_place_year_in_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('historical', 'historical'), ('local culture', 'local culture'), ('local cusine', 'local cusine'), ('relaxation', 'relaxation')], default='historical', max_length=50),
        ),
    ]
