# Generated by Django 2.2 on 2019-04-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripPackages', '0004_auto_20190416_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='place',
            name='brief',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='place',
            name='location',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
