# Generated by Django 2.2 on 2019-04-07 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Date_of_birth',
        ),
    ]
