# Generated by Django 2.2 on 2019-04-08 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0007_auto_20190408_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
