# Generated by Django 2.2 on 2019-04-08 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0008_remove_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
    ]
