# Generated by Django 2.2 on 2019-04-08 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0009_remove_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_of_birth'),
        ),
    ]
