# Generated by Django 2.2 on 2019-04-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0010_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='phone number'),
        ),
    ]
