# Generated by Django 2.2 on 2019-04-08 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0011_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
